### ISSUE TITLE
Errore in esecuzione

### ISSUE THREAD

**Issue by Sblackk** [Home-Assistant-Pro-Team/Alexa-actionable-notification-rooms-presence#1]
Buona sera... mi sono imbattuto casualmente in questo progetto e l'ho subito trovato pratico ed utile.

Purtroppo non riesco a farlo funzionare. Selezionati i sensori, la latenza e la frase da riprodurre nell'echo dot, salvo l'automazione.

Il trigger funziona in  modo impeccabile, ma non riesce ad attivare lo script  "activate_alexa_actionable_notification", che già uso da diverso tempo.

Nel registro di sistema, genera i seguenti errori:

---------------------------------------------------------------------------------------------------------------------------------------------------
Registratore: homeassistant.helpers.template
Fonte: helpers/template.py:2377
Prima occorrenza: 12 marzo 2024 alle ore 19:30:45 (25 occorrenze)
Ultima registrazione: 17:04:46

Template variable warning: No first item, sequence was empty. when rendering '{{ states.media_player | selectattr('attributes.last_called','eq',True) | map(attribute='entity_id') | first }}'
Template variable warning: 'dict object' has no attribute 'entity_id' when rendering '{{ area_name(trigger.entity_id) }}'
Template variable warning: 'suppress_confirmation' is undefined when rendering '{"text": "{{ text }}", "event": "{{ event_id }}", "suppress_confirmation": "{{ suppress_confirmation }}"}'

---------------------------------------------------------------------------------------------------------------------------------------------------
Registratore: homeassistant.components.automation.11111alexa_actionable_notification_rooms_presence
Fonte: helpers/script.py:1805
integration: Automazione (documentazione, problemi)
Prima occorrenza: 10:10:56 (5 occorrenze)
Ultima registrazione: 17:04:46

11111Alexa actionable notification rooms presence.: Error executing script. Error for call_service at pos 1: Error rendering data template: TypeError: can only concatenate str (not "NoneType") to str

---------------------------------------------------------------------------------------------------------------------------------------------------
Registratore: homeassistant.components.automation.11111alexa_actionable_notification_rooms_presence
Fonte: components/automation/__init__.py:687
integration: Automazione (documentazione, problemi)
Prima occorrenza: 10:10:56 (5 occorrenze)
Ultima registrazione: 17:04:46

Error while executing automation automation.11111alexa_actionable_notification_rooms_presence: Error rendering data template: TypeError: can only concatenate str (not "NoneType") to str

---------------------------------------------------------------------------------------------------------------------------------------------------

Mi servirebbe un pò di aiuto per risolvere. Grazie mille...

**Comment by marco-hacs** [comment]
hai associato le aree ai dispositivi? 
verifica come prima cosa con questo: {{ area_name(entity_id) }}
e controllo che questo template ti restituisca un nome di un media_player alexa {{ states.media_player | selectattr('attributes.last_called','eq',True) | map(attribute='entity_id') | first }}

**Comment by Sblackk** [comment]
Tutto risolto, grazie...
